# Generated by Django 6.1.1 on 2026-09-16 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name_ky', models.CharField(max_length=64, verbose_name='Аталышы (кыргызча)')),
                ('description_ky', models.CharField(blank=True, default='', max_length=160, verbose_name='Сүрөттөмө (кыргызча)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rewards/furniture/')),
                ('category', models.CharField(choices=[('table', 'Үстөл'), ('chair', 'Отургуч'), ('bed', 'Төшөк'), ('carpet', 'Килем'), ('shyrdak', 'Шырдак'), ('chest', 'Сандык'), ('clothing', 'Улуттук кийим'), ('decor', 'Жасалга')], max_length=16)),
                ('price', models.PositiveIntegerField(help_text='Баасы тыйын менен')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Бөлмө буюму',
                'verbose_name_plural': 'Бөлмө буюмдары',
                'ordering': ['category', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.CharField(choices=[('uy', 'Заманбап үй бөлмөсү'), ('boz_ui', 'Боз үй')], default='uy', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Бөлмө',
                'verbose_name_plural': 'Бөлмөлөр',
            },
        ),
        migrations.CreateModel(
            name='UserFurniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_placed', models.BooleanField(default=True, help_text='Учурда бөлмөдө көрсөтүлүп жатабы')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_by', to='rooms.furniture')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_furniture', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Сатылып алынган буюм',
                'verbose_name_plural': 'Сатылып алынган буюмдар',
                'constraints': [models.UniqueConstraint(fields=('profile', 'furniture'), name='unique_profile_furniture')],
            },
        ),
    ]
