# Generated by Django 6.1.1 on 2026-09-16 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words_learned_count', models.PositiveIntegerField(default=0)),
                ('items_found_count', models.PositiveIntegerField(default=0)),
                ('quests_completed_count', models.PositiveIntegerField(default=0)),
                ('correct_answers_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Колдонуучунун прогресси',
                'verbose_name_plural': 'Колдонуучулардын прогресстери',
            },
        ),
        migrations.CreateModel(
            name='DiscoveredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_by', to='items.item')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_items', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Табылган буюм',
                'verbose_name_plural': 'Табылган буюмдар',
                'constraints': [models.UniqueConstraint(fields=('profile', 'item'), name='unique_profile_item_discovery')],
            },
        ),
    ]
