# Generated by Django 6.1.1 on 2026-09-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('name_ky', models.CharField(max_length=64, verbose_name='Аталышы (кыргызча)')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='ui/categories/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категориялар',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('name_ky', models.CharField(max_length=64, verbose_name='Аталышы (кыргызча)')),
                ('description_ky', models.TextField(blank=True, default='', verbose_name='Сүрөттөмө (кыргызча)')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='locations/backgrounds/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('unlock_level', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локациялар',
                'ordering': ['order', 'id'],
            },
        ),
    ]
