# Generated by Django 6.1.1 on 2026-09-16 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('title_ky', models.CharField(max_length=64, verbose_name='Аталышы (кыргызча)')),
                ('description_ky', models.CharField(max_length=160, verbose_name='Сүрөттөмө (кыргызча)')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='rewards/achievements/')),
                ('condition_type', models.CharField(choices=[('items_found', 'Табылган буюмдардын саны'), ('quests_completed', 'Аяктаган тапшырмалардын саны'), ('words_learned', 'Үйрөнгөн сөздөрдүн саны'), ('correct_answers', 'Туура жооптордун саны')], max_length=32)),
                ('threshold', models.PositiveIntegerField(help_text='Мисалы: 10 (10 сөз үйрөнгөндө ачылат)')),
                ('reward_coins', models.PositiveIntegerField(default=0, help_text='Ачылганда кошумча берилүүчү тыйын (милдеттүү эмес)')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Жетишкендик',
                'verbose_name_plural': 'Жетишкендиктер',
                'ordering': ['order', 'threshold'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_by', to='achievements.achievement')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_achievements', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Ачылган жетишкендик',
                'verbose_name_plural': 'Ачылган жетишкендиктер',
                'ordering': ['-unlocked_at'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'achievement'), name='unique_profile_achievement')],
            },
        ),
    ]
