# Generated by Django 6.1.1 on 2026-09-16 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Оң сан — кирешe, терс сан — чыгаша')),
                ('reason', models.CharField(choices=[('item_discovered', 'Буюм табылды'), ('quest_completed', 'Тапшырма аткарылды'), ('bonus', 'Бонус')], max_length=32)),
                ('source_type', models.CharField(blank=True, default='', max_length=32)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_transactions', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Тыйын транзакциясы',
                'verbose_name_plural': 'Тыйын транзакциялары',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['profile', 'source_type', 'source_id'], name='rewards_rew_profile_edce96_idx')],
            },
        ),
    ]
