# Generated by Django 6.1.1 on 2026-09-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardtransaction',
            name='reason',
            field=models.CharField(choices=[('item_discovered', 'Буюм табылды'), ('quest_completed', 'Тапшырма аткарылды'), ('bonus', 'Бонус'), ('furniture_purchase', 'Буюм сатылып алынды')], max_length=32),
        ),
    ]
