# Generated by Django 6.1.1 on 2026-09-16 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('items', '0001_initial'),
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_type', models.CharField(choices=[('find_item', 'Буюмду тап')], default='find_item', max_length=16)),
                ('prompt_ky', models.CharField(help_text='Мисалы: "Чыныны тап."', max_length=128, verbose_name='Тапшырма тексти (кыргызча)')),
                ('reward_coins', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('correct_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests_as_answer', to='items.item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='worlds.location')),
            ],
            options={
                'verbose_name': 'Тапшырма',
                'verbose_name_plural': 'Тапшырмалар',
            },
        ),
        migrations.CreateModel(
            name='QuestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('reward_granted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_attempts', to='accounts.profile')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quests.quest')),
                ('selected_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
            options={
                'verbose_name': 'Тапшырмага аракет',
                'verbose_name_plural': 'Тапшырмага аракеттер',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quests.quest')),
            ],
            options={
                'verbose_name': 'Тапшырманын варианты',
                'verbose_name_plural': 'Тапшырманын варианттары',
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('quest', 'item'), name='unique_quest_item_option')],
            },
        ),
    ]
