# Generated by Django 6.1.1 on 2026-09-16 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name_ky', models.CharField(max_length=64, verbose_name='Аталышы (кыргызча)')),
                ('description_ky', models.TextField(verbose_name='Сүрөттөмө (кыргызча)')),
                ('cultural_fact_ky', models.TextField(blank=True, default='', verbose_name='Маданий факт (кыргызча)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/items/')),
                ('difficulty', models.CharField(choices=[('easy', 'Жеңил'), ('medium', 'Орто'), ('hard', 'Кыйын')], default='easy', max_length=8)),
                ('discover_reward', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='worlds.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='worlds.location')),
            ],
            options={
                'verbose_name': 'Буюм',
                'verbose_name_plural': 'Буюмдар',
                'ordering': ['location', 'category', 'name_ky'],
            },
        ),
    ]
